Tencent/tdesign

.github/workflows/issues-statistics-dispatch.yml, .github/workflows/issues-statistics-schedule.yml, .github/workflows/issues-statistics.yml, .gitignore
=> ci: 给 create-report  添加定时和手动触发

.github/workflows/preview.yml
=> ci: 修复已有评论是不展示pr的问题

.github/workflows/issue-help-wanted.yml
=> ci: 优化 issue help wanted

.github/workflows/preview.yml
=> feat: preview target

.github/workflows/issue-stale-close.temp.yml, .github/workflows/preview.yml
1、a 标签 blank 无效
2、issue 自动过期提醒的时间和实际对不上
=> chore: 优化一些 actions 文案

.github/workflows/demo/test-build-demo.yml, README.md
1. 添加 tdesign-react-starter 仓库链接
=> docs: add react-starter

.github/actions/create-report/const.js, .github/actions/create-report/dist/index.js
=> ci: 日报添加react-star

README.md
=> docs: update readme 开放 mobile-vue 仓库

src/components/IssueForm/index.tsx
=> feat: 优化 issue helper 模板

.github/workflows/demo/pr-compressed-size.yml, .github/workflows/pr-spelling.template.yml
=> ci: add pr-spelling

.github/workflows/publish.yml
=> feat: 支持发布版本后自动更新站点逻辑

.github/workflows/publish.yml
=> fix: auto publish

.github/workflows/publish.yml
=> feat: auto publish

docs/contributing.md
=> docs: 修正错误描述

README.md
=> docs: update version info

README.md, docs/introduce.md
=> docs: 调整文档

.github/workflows/issue-assignees.temp.yml
=> feat: 招募类组件关闭自动回复

.github/workflows/issue-assignees.temp.yml
=> feat: 支持自动回复过滤新组件和 issueshoot

docs/design/TDesign_Axure_Library 使用手册
=> TDesign_Axure_Library Guide

README.md, docs/introduce.md, docs/roadmap.md
=> feat: react 发布lts

.github/workflows/issue-synchronize.temp.yml, .github/workflows/issues-dailyclose-schedule.yml, .github/workflows/issues-statistics-schedule.yml
=> ci(report): 修改 report 仓库源

.github/workflows/publish.yml, .github/workflows/test-build.yml
=> feat: update node

docs/new-component.md, docs/new-component_zh-CN.md
=> docs: en version for new component

.github/workflows/publish.yml
=> ci: update npm publish

.github/workflows/test-build.yml
- hybirds required 18
- chore: fix build CI workflow 
=> chore: update site build node version

docs/develop-install.md
=> docs: update develop-install.md

docs/design/offices-task_zh-CN.md, packages/components/README.md, packages/theme-generator/README.md, site/README.md
- docs: update design docs content
=> docs: update design docs and README

packages/components/src/components/td-header/portal.less
https://github.com/Tencent/tdesign/issues/386
- fix: 修正header样式溢出
=> fix: 修正header样式溢出

packages/components/config/header.js, packages/components/package.json
- chore: 更新 `mobile-vue` 组件库状态
=> chore: update library status

docs/awesome.md, docs/awesome_zh-CN.md, docs/roadmap.md, docs/roadmap_zh-CN.md
=> docs: update community content

docs/design/TDesign_Axure_Library Guide.md
=> docs: update TDesign_Axure_Library Guide.md

.commitlintrc.js, .eslintrc.js, .husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, .prettierrc.js, .stylelintrc.js, package.json, packages/components/.eslintrc.js, packages/theme-generator/.eslintrc.js, packages/theme-generator/package.json, packages/theme-generator/src/common/utils/vars.css, pnpm-lock.yaml
增加 `eslint` `prettier` `stylelint` 规范
- chore: add eslint prettier stylelint rule
- fix: fix vars.css
=> chore: add eslint rule

README_zh-CN.md
=> chore: update README

packages/components/package.json
- chore: site-component release 0.13.13
=> chore: site-component release 0.13.13

package.json, packages/components/.eslintrc.js, packages/components/package.json, packages/components/src/components/td-header/index.js
=> chore: replace intranet repo and script

docs/introduce.md, docs/introduce_zh-CN.md
=> docs: update introduce

site/src/pages/design/fonts_zh-CN.vue
Change download link
- 修改字体下载链接
=> docs: update fonts download url

.stylelintrc.js, packages/components/src/components/td-doc-phone/index.js, packages/components/src/components/td-doc-phone/style.less, packages/components/src/images/jump.svg
目前 `doc-phone` 组件不支持新窗口直接打开链接，不方便调试
增加 `href` 属性，设置该属性后显示新窗口打开图标
- feat(doc-phone): support href link
=> feat: doc-phone support href link

packages/components/package.json
=> chore: release 0.13.15

packages/components/src/components/td-doc-aside/index.js
- fix(site-component): nav update tag doesn't toggle active
=> fix(site-component): nav update tag doesn't toggle active

packages/components/package.json
=> chore: release 0.13.17

README.md, README_zh-CN.md, packages/components/src/components/td-header/index.js
=> chore: update flutter repo info

packages/components/src/components/td-stats/index.js
=> chroe: change analytics src

packages/components/package.json
=> chore: release 0.13.19

packages/components/src/components/td-doc-footer/index.js
=> chore: update end year of copyright

packages/components/package.json
=> chore: release 0.13.20

packages/components/src/components/td-header/portal.less
修正 header 组件的弹层在 `< 960px` 页面没有隐藏的问题
- fix(td-header): hidden header links
=> fix(td-header): hide header links

site/src/consts.js
=> chore: update sketch assets url

packages/components/package.json
- chore(site-components): release 0.13.21
=> chore: release 0.13.21

packages/components/config/mock.js, packages/components/index.html, packages/components/src/components/td-doc-demo/index.js, packages/components/src/components/td-doc-demo/style.less
=> feat: support various demos

packages/components/src/components/td-doc-demo/index.js
- fix(site-components): 修复`0.14.0`代码复制功能不正常的问题
=> fix(site-components): fix copy

packages/components/package.json
- chore(site-components): release 0.14.1
=> chore: release 0.14.1

services/notice.json
=> chore: update notice for vue-next

services/notice.json
=> chore: update notice for vue

packages/components/src/components/td-doc-demo/style.less
=> fix: fix demo code height

packages/components/package.json
=> chore: release 0.14.2

packages/components/package.json
=> chore: release 0.14.3

packages/components/src/components/td-doc-demo/index.js
- fix(site-components): fix demo tab style
=> fix: fix demo tab style

packages/components/package.json
=> chore: release 0.14.4

packages/components/package.json
=> chore: release 0.14.5

packages/components/package.json
- https://github.com/Tencent/tdesign/pull/462 by @loo2k 
- chore: release 0.14.6
=> chore: release 0.14.6

docs/introduce.md, docs/introduce_zh-CN.md
- docs: update tdesign-flutter status
=> docs: update tdesign-flutter status

.github/workflows/typos-config.toml, docs/design/offices-task.md, site/src/docs/design/offices-task.md
=> chore: spell check config

.github/workflows/preview-site.yml, .github/workflows/test-build-site.yml
=> feat: support preview

packages/components/package.json
=> chore: release 0.14.7

packages/components/src/components/td-header/index.js
- fix(site-components):  rename `enabledLocale` as `disabledLocale`
=> fix: rename locale control

packages/components/package.json
=> chore: release 0.15.0

packages/components/package.json
=> chore: release 0.15.1

packages/components/config/footer.js, packages/components/config/index.js, packages/components/src/components/td-logo/index.js
- feat: remove deprecated platform 
=> feat: remove deprecated platform

packages/components/package.json
=> chore: release 0.15.2

docs/roadmap.md, docs/roadmap_zh-CN.md, packages/theme-generator/src/common/utils/index.js
=> docs: update roadmap docs

docs/awesome.md, docs/awesome_zh-CN.md
- docs: increase community resources `fantastic-admin`
=> docs: increase community resources

.github/workflows/test-build.yml
=> ci(test-build): add test build

services/notice.json
=> chore: update notice file

services/update-components-notice.js
=> chore: fix ci

services/notice.json
=> chore: update notice.json

packages/components/config/index.js, packages/components/package.json, packages/components/src/components/td-logo/index.js
=> chore: release 0.15.3

docs/introduce.md, docs/introduce_zh-CN.md
=> docs: update repo link

docs/contact.md, docs/contact_zh-CN.md
=> docs: update contact docs

services/notice.json
=> chore: update notice

packages/components/config/spline.js
- feat: add ai spline banner resource
=> feat: add AI spline banner resource

packages/components/package.json
- chore: release site-components 0.15.4
=> chore: release 0.15.4

docs/contact.md, docs/contact_zh-CN.md
=> docs: update contact

.github/workflows/service-update-schedule.yml
=> ci(service-update-schedule): prevents this action from running on forks

pnpm-lock.yaml, site/package.json
- fix: fix homepage transition
=> chore: fix homepage transition

site/src/pages/home/index.vue, site/src/pages/home/index_zh-CN.vue, site/src/style/home.less
=> chore: fix style and content

site/src/style/home.less
=> fix: news scrollbar

site/src/style/home.less
=> fix: fix style

.github/workflows/issue-assignees.temp.yml, .github/workflows/preview.yml
=> chore: upgrade actions-cool/maintain-one-comment@v3

.github/.pr-comment-ci-whitelist
=> chore:  add .pr-comment-ci-whitelist

.github/.pr-comment-ci-whitelist
=> chore: update .pr-comment-ci whitelist

.github/workflows/demo/pr-compressed-size.yml, .github/workflows/issue-mark-duplicate.temp.yml, .github/workflows/issue-reply.temp.yml, .github/workflows/issues-dailyclose-schedule.yml, .github/workflows/issues-dailynew-schedule.yml, .github/workflows/issues-statistics-schedule.yml, .github/workflows/pr-spelling.template.yml, .github/workflows/preview.yml, .github/workflows/publish-components.yml, .github/workflows/publish.yml, .github/workflows/pull-request.yml, .github/workflows/service-update-schedule.yml, .github/workflows/test-build-site.yml
=> chore: upgrade ci action version

packages/theme-generator/src/common/built-in/themes/#0052D9.css
=> chore: fix font default config

packages/theme-generator/package.json
- chore: release theme-generator 1.0.16
=> chore: release theme-generator 1.0.16

.github/workflows/auto-release.yml
- fix: fix trigger auto release time
=> chore: fix auto release time

.github/workflows/preview.yml
=> chore: update preview surge.sh domain

pnpm-lock.yaml, services/notice.json, site/package.json
=> chore: icon release update and notice

packages/components/src/components/td-header/index.js
- chore: replace version request url
=> chore: replace version request

packages/components/src/components/td-header/index.js
=> chore: filter request

packages/components/package.json
=> chore: release 0.15.5

pnpm-lock.yaml, site/package.json
=> chore: update dep

packages/components/package.json, packages/components/src/components/td-header/index.js
=> chore: replace api and release version

packages/auto-release/src/constants.ts
waitting 
https://github.com/Tencent/tdesign-react-starter/pull/186
https://github.com/Tencent/tdesign-vue-starter/pull/327
- chore(auto-release): 添加多个收集信息 release 日志仓库
=> chore(auto-release): add starter changelog 

.github/workflows/test-build.yml
邮箱检查忽略 tdesign-bot@tencent.com
=> ci(test-build): update check mail

.github/workflows/test-build.yml
=> ci(test-build): fix check mail

.github/workflows/test-build.yml
=> ci(check-mail): update ignore email

services/notice.json
=> chore: update notices

.github/ISSUE_TEMPLATE/bug-report.zh-CN.yml
=> chore: update bug-report.zh-CN.yml

packages/theme-generator/src/common/utils/vars.css
- fix: fix footer render in mobile devices
=> chore: remove variables from theme-generator

packages/components/package.json
- https://github.com/Tencent/tdesign/pull/593
- chore: release 0.15.7
=> chore: release 0.15.7

packages/theme-generator/package.json
- chore: release theme generator 1.0.17
=> chore: release theme generator 1.0.17

.github/.pr-comment-ci-whitelist
=> chore: update auto ci whitelist

.github/.pr-comment-ci-whitelist
=> chore: fix whitelist

.github/ISSUE_TEMPLATE/bug-report.zh-CN.yml, .github/ISSUE_TEMPLATE/feature-report.zh-CN.yml
当用户每提出一个问题的时候都会自动打上对应类别标签，另会打上一个 no-confirm 的标签用来标记他还没有被审查。
=> chore: add default issue labels

packages/theme-generator/src/common/Themes/built-in/css/mobile/common/spacer.css, packages/theme-generator/src/common/Themes/iframe.js, packages/theme-generator/src/common/Themes/preset.js
- [fix(theme-generator): handle cases with nested iframes in mini-program
=> fix(theme-generator): handle cases with nested iframes in mini-program

packages/theme-generator/package.json
- chore: theme-generator 1.1.1
=> chore: theme-generator 1.1.1

packages/components/package.json, packages/components/src/components/td-doc-header/td-doc-issue/index.js
=> chore: release 0.15.8

packages/theme-generator/package.json, packages/theme-generator/src/common/Themes/index.js
- fix(theme-generator): use normalized device for comparison
=> fix(theme-generator): use normalized device for comparison

packages/components/package.json, packages/components/src/components/td-doc-header/td-doc-issue/index.js
- chore: remove intranet issue address
=> chore: release 0.15.9

services/notice.json
-  🎉 移动端整体接入主题生成器 by @RylanBot
=> docs: update notice

packages/theme-generator/src/common/Themes/index.js
- chore(theme-generator): update CSS selector for Mini Program export
=> chore(theme-generator): update CSS selector for Mini Program export

packages/components/package.json, packages/theme-generator/package.json
补充repository 为后续接入pkg.pr.new 做准备
=> chore(package.json): add repository url

packages/theme-generator/package.json, pnpm-lock.yaml, site/package.json
=> chore: version release

.github/workflows/pkg-pr-new.yml, package.json
=> ci: add  pkg-pr-new

.github/.pr-comment-ci-whitelist
=> chore: update CI whitelist

.github/workflows/auto-release.yml
=> fix(ci): auto-release operating environment pnpm version

pnpm-lock.yaml, site/package.json, site/vite.config.js
=> chore(site): upgrade vite6

packages/components/src/components/td-header/style.less
=> fix(header-notice): fix height

packages/components/package.json
=> chore: release 0.15.10

.github/workflows/publish-components.yml
- https://github.com/Tencent/tdesign/actions/runs/14993848237
=> chore: fix publish components ci

packages/components/config/footer.js
=> feat(site): add TEditor link

docs/roadmap.md, docs/roadmap_zh-CN.md, pnpm-lock.yaml, site/package.json
=> docs: update roadmap

packages/auto-release-collection/src/constants.ts, packages/auto-release-collection/src/index.ts, packages/auto-release-collection/src/utils.ts
=> chore(auto-release-collection): adapt to the new version of Vue3 for Web release

.github/workflows/pkg-pr-new.yml, .github/workflows/publish-components.yml, .github/workflows/pull-request.yml
=> ci: add condition runing

packages/components/config/locale.js, packages/components/package.json, packages/components/src/components/td-doc-aside/index.js, packages/components/src/components/td-doc-changelog/index.js, packages/components/src/components/td-doc-changelog/style.less, packages/components/src/components/td-doc-content/index.js, packages/components/src/components/td-doc-header/index.js, packages/components/src/components/td-doc-header/style.less, packages/components/src/components/td-doc-popup/index.js, packages/components/src/components/td-header/index.js, packages/components/src/main.js, packages/components/src/styles/docs.less, packages/components/src/utils/index.js, packages/components/vite.config.js
**组件库端需要配合具体的 Markdown -> JSON 脚本，生成一份 `changelog.json` 在 `public` 下**
- https://github.com/Tencent/tdesign-react/pull/3618
**(其它变动)**
- 将 `postbuild` 的脚本作为 Vite Plugin，否则本地 `vite build --watch` 开发时，样式文件无法同步
- 优化交互逻辑，初始化时自动滚动页面，让选中的 `nav` 在 可视化范围内
- 调整一些样式，更好适配移动端
- feat(site): 每个组件文档页面新增单独的 Changelog
=> feat(site): add a changelog for each component page

packages/components/package.json, packages/components/src/components/td-doc-changelog/index.js, packages/components/src/components/td-doc-changelog/style.less, packages/components/src/components/td-doc-header/index.js, packages/components/src/components/td-doc-header/style.less
=> chore: release 0.16.0

packages/components/package.json, packages/theme-generator/package.json
- chore: release tdesign-theme-generator 1.1.6
- chore: release tdesign-site-components 0.16.0
=> chore: release version

packages/components/package.json, packages/components/src/components/td-doc-aside/style.less, packages/components/src/components/td-doc-header/index.js, packages/components/src/components/td-doc-header/style.less, packages/components/src/styles/docs.less, packages/components/src/utils/index.js
- 支持条件渲染变更日志按钮，写法：`<td-doc-header changelog={false} />`
- 顺便调整了一些样式适配移动端，例如表格异常等
- https://github.com/Tencent/tdesign/issues/678
=> fix(td-doc-changelog): conditionally render button

packages/components/src/components/td-doc-changelog/index.js, packages/components/src/utils/index.js
- fix(sit-components): changelog add special component lookup
=> fix(td-doc-changelog): optimize special component name lookup

packages/components/src/components/td-doc-header/index.js
用于支持显示 or 隐藏 头部内容中右下角的 “issue” 内容
- feat(td-doc-header): 新增 `showIssue` 属性
=> feat(td-doc-header): support showIssue prop

docs/contact.md, docs/contact_zh-CN.md, site/src/pages/home/index.vue, site/src/pages/home/index_zh-CN.vue
fix https://github.com/Tencent/tdesign/issues/700
=> docs: disable auto-switching of swiper after focus

packages/components/src/styles/docs.less
=> fix(style): abnormal thumbnail width

site/src/pages/home/index.vue, site/src/pages/home/index_zh-CN.vue
=> docs(site): update codeFramework

packages/site-components/package.json
=> chore: release 0.17.1

.github/workflows/publish.yml
=> chore: merges remote develop, uses its code for conflicts.

packages/site-components/src/components/td-doc-changelog/index.js, packages/site-components/src/components/td-doc-changelog/style.less
现在：
更新后：
- fix(td-doc-changelog): 统一使用 `<td-code />` 渲染行内代码
=> fix(td-doc-changelog): update code rendering
